version: '3.8'

services:
  mongodb-test:
    image: mongo:7.0
    container_name: mongodb-test
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=vendor-integration-test
    volumes:
      - mongodb_test_data:/data/db
    command: mongod --quiet --logpath /dev/null
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-test:
    image: redis:7-alpine
    container_name: redis-test
    ports:
      - "6379:6379"
    command: redis-server --appendonly no --save ""
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_test_data: 